#!/bin/sh
set -euf

if [ "${#}" -ne 3 ]; then
  echo "Usage: $0 X Y Z" >&2
  exit 1
fi

GIT_BRANCH=$(git rev-parse --abbrev-ref HEAD)
GIT_HASH=$(git rev-parse --short HEAD)

{
echo "#pragma once"
echo "// This file was autogenerated by cmake/generate-version.sh"
echo "//   creation date: $(LANG=en_US date '+%A %d %B %Y %H:%M:%S')"
echo "#include <stdint.h>"
echo "static constexpr uint8_t C_VERSION_MAJOR{${1}};"
echo "static constexpr uint8_t C_VERSION_MINOR{${2}};"
echo "static constexpr uint8_t C_VERSION_PATCH{${3}};"
echo "static constexpr const char C_VERSION[]{\"${1}.${2}.${3}\"};"
echo "static constexpr const char C_GIT_BRANCH[]{\"${GIT_BRANCH}\"};"
echo "static constexpr const char C_GIT_HASH[]{\"${GIT_HASH}\"};"
echo "static constexpr const char C_VERSION_VERBOSE[]{\"${1}.${2}.${3}-${GIT_BRANCH}-${GIT_HASH}\"};"
} > "${PWD}/src/version.hpp"
