# Trigger generation of src/version.h everytime the git HEAD changes
if(EXISTS "${CMAKE_CURRENT_SOURCE_DIR}/.git")
  # The repository is cloned individually
  if(IS_DIRECTORY "${CMAKE_CURRENT_SOURCE_DIR}/.git")
    set(GIT_DIR "${CMAKE_CURRENT_SOURCE_DIR}/.git")
    # The repository is cloned as a git submodule
  else()
    execute_process(
      COMMAND cut -d " " -f 2 .git
      WORKING_DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR}
      OUTPUT_VARIABLE SUBMODULE_GIT_DIR
      OUTPUT_STRIP_TRAILING_WHITESPACE)
    set(GIT_DIR "${CMAKE_CURRENT_SOURCE_DIR}/${SUBMODULE_GIT_DIR}")
  endif()
  # Add command that is triggered again every time the git HEAD changes
  add_custom_command(
    OUTPUT ${CMAKE_CURRENT_SOURCE_DIR}/src/version.h
    COMMAND echo "\// This file is autogenerated by generate-version.cmake\n\
    #pragma once\n\
    #include <stdint.h>\n\
    static constexpr uint8_t C_VERSION_MAJOR{${CMAKE_PROJECT_VERSION_MAJOR}};\n\
    static constexpr uint8_t C_VERSION_MINOR{${CMAKE_PROJECT_VERSION_MINOR}};\n\
    static constexpr uint8_t C_VERSION_PATCH{${CMAKE_PROJECT_VERSION_PATCH}};\n\
    static constexpr const char C_VERSION[]{\"${CMAKE_PROJECT_VERSION_MAJOR}.${CMAKE_PROJECT_VERSION_MINOR}.${CMAKE_PROJECT_VERSION_PATCH}\"};\n\
    static constexpr const char C_GIT_BRANCH[]{\"$(git rev-parse --abbrev-ref HEAD)\"};\n\
    static constexpr const char C_GIT_HASH[]{\"$(git rev-parse --short HEAD)\"};\n"
    COMMENT "Regenerating src/version.h"
    WORKING_DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR}
    DEPENDS ${GIT_DIR}/logs/HEAD
    VERBATIM)
  # COMMAND scripts/generate-version-header.sh ${CMAKE_PROJECT_VERSION_MAJOR}
  # ${CMAKE_PROJECT_VERSION_MINOR} ${CMAKE_PROJECT_VERSION_PATCH}
else()
  message(
    FATAL_ERROR
      "Couldn't generate version.h file: .git repository was not found")
endif()
