#!/bin/sh
set -euf

cd "$(dirname "$0")"/..

if [ "${#}" -ne 3 ]; then
  echo "Usage: $0 X Y Z" >&2
  exit 1
fi

{
echo "#pragma once"
echo "// This file was autogenerated by cmake/generate-version.sh"
echo "//   creation date: $(LANG=en_US date '+%A %d %B %Y %H:%M:%S')"
echo "#include <stdint.h>"
echo "static constexpr uint8_t C_VERSION_MAJOR{${1}};"
echo "static constexpr uint8_t C_VERSION_MINOR{${2}};"
echo "static constexpr uint8_t C_VERSION_PATCH{${3}};"
echo "static constexpr const char C_VERSION[]{\"${1}.${2}.${3}\"};"
echo "static constexpr const char C_GIT_BRANCH[]{\"$(git rev-parse --abbrev-ref HEAD)\"};"
echo "static constexpr const char C_GIT_HASH[]{\"$(git rev-parse --short HEAD)\"};"
} > src/version.h
